### ISSUE TITLE
Porting SSHIQ

### ISSUE THREAD

**Issue by GMJCZP** [Asd-g/AviSynth-SmoothUV2#2] opened 2021-05-27 11:09 UTC
Hello, I have been a regular user of the SmoothUV plugin for several years, specifically SSHiq (it is my favorite Denoiser space) and I would like it to be included in the new SmoothUV. Thank you very much in advance.

**Comment by Asd-g** [comment] 2021-06-04 17:21
I will check it but no eta.

**Comment by Asd-g** [comment] 2021-06-08 17:57
You can try the new version.

**Comment by kedaitinh12** [comment] 2021-06-08 23:10
Thanks

**Comment by GMJCZP** [comment] 2021-06-09 10:56
Thanks for the contribution but my CPU is a Dual Core E5800 and I get the following error message: "Avisynth open failure: System exception - Illegal Instruction".

**Comment by realfinder** [comment] 2021-06-09 11:54
maybe it's better to add C code, for GMJCZP case and also non x86/x64 CPUs

**Comment by Asd-g** [comment] 2021-06-13 05:18
Ok.

**Comment by Asd-g** [comment] 2021-06-24 22:02
@GMJCZP, you can try the latest version.

**Comment by GMJCZP** [comment] 2021-06-26 03:53
Thanks for the upload, I'll go try it.

**Comment by GMJCZP** [comment] 2021-06-26 10:45
I am getting this message error: "Error reading source frame 0: Avisynth read error: CAVIStreamSynth: System exception - Illegal Instruction at 0x6CB73AE5".

**Comment by Asd-g** [comment] 2021-06-26 16:51
What's the version of avs+?
What's the used script?
Can you share a short sample of the used clip?
What program is used for running the script - avspmod/virtualdub/megui/staxrip... ?
Any difference with [this build](https://srv-store1.gofile.io/download/8a1dc446-0311-456b-942a-c4f700353e6d/smoothuv2.7z)?

**Comment by kedaitinh12** [comment] 2021-06-27 00:14
Your link error @Asd-g 
![Screenshot_20210627_071313](https://user-images.githubusercontent.com/66716952/123529046-3fd3d900-d717-11eb-9965-0fc058b682c9.jpg)

**Comment by GMJCZP** [comment] 2021-06-27 01:39
I am using Avs + 3.7. on Windows 7 32-bit. The script and the source are irrelevant, I have tested in avi's and mp4's with different scripts and nothing to do in VDub2, VirtualDubMod and MPC-HC.

Edit: the link not working.

**Comment by Asd-g** [comment] 2021-06-27 02:34
This link should be fine - https://gofile.io/d/8qFvSo

> 
> 
> I am using Avs + 3.7. on Windows 7 32-bit. The script and the source are irrelevant, I have tested in avi's and mp4's with different scripts and nothing to do in VDub2, VirtualDubMod and MPC-HC.

I cannot reproduce the error you have. Without knowing at least the script that can reproduce the error, I cannot do much.
You can try add convertbits(16) before and convertbits(8) after the call:
```
...
convertbits(16)
sshiq2()
convertbits(8)
...
```

**Comment by GMJCZP** [comment] 2021-06-27 13:26
The file I downloaded from the link you passed is for compiling, I thought it was another version of Smoothuv2.

The script you posted doesn't work either.

Sample:
http://www.filedropper.com/sample2_1

Here the script:

LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
sshiq2(rY=5,rC=5,tY=5,tC=5,str=5,HQC=false,HQY=true)

Remember that my CPU is e5800 dual core.

**Comment by realfinder** [comment] 2021-06-27 17:01
I think the problem here https://github.com/Asd-g/AviSynth-SmoothUV2/blob/8809f6f2e7e89e0845694cb4281e9d7a29fb5f0f/CMakeLists.txt#L27

**Comment by kedaitinh12** [comment] 2021-06-27 23:32
I think the problem here https://github.com/Asd-g/AviSynth-SmoothUV2/blob/8809f6f2e7e89e0845694cb4281e9d7a29fb5f0f/CMakeLists.txt#L27

**Comment by GMJCZP** [comment] 2021-06-28 00:33
Ok, interesting, my processor e5800 is not capable for sse4 instructions.

**Comment by Asd-g** [comment] 2021-06-28 04:00
> 
> 
> The file I downloaded from the link you passed is for compiling, I thought it was another version of Smoothuv2.
> 
> The script you posted doesn't work either.
> 
> Sample:
> http://www.filedropper.com/sample2_1
> 
> Here the script:
> 
> LWLibavVideoSource("Sample2.mp4")
> AssumeFPS("ntsc_film")
> sshiq2(rY=5,rC=5,tY=5,tC=5,str=5,HQC=false,HQY=true)
> 
> Remember that my CPU is e5800 dual core.

I tested the 32-bit version on Windows 10 x64 with opt=0 and then with SetMaxCPU("none"). I couldn't reproduce the error.
@realfinder, @kedaitinh12 can you reproduce the error?

Something to test:
- Any difference if you remove AssumeFPS("ntsc_film")?
- Try with SetMemoryMax(120) at the top of the script.
- Try this version - https://gofile.io/d/umC293

How much RAM do you have?

> 
> 
> I think the problem here
> 
> https://github.com/Asd-g/AviSynth-SmoothUV2/blob/8809f6f2e7e89e0845694cb4281e9d7a29fb5f0f/CMakeLists.txt#L27

This is irrelevant: cmake is used for Linux builds (read the bottom of README.md) and the SSE4.1 code is separated in SmoothUV2_SSE41.cpp.

**Comment by realfinder** [comment] 2021-06-28 04:07
> 
> 
> @realfinder, @kedaitinh12 can you reproduce the error?
> 
I can't, so maybe it's something about compiling, kedaitinh12 comment was done by me but I did delete it since for windows there are Solution (.Sln), kedaitinh12 maybe copy it from email and repost it

**Comment by realfinder** [comment] 2021-06-28 04:14
don't know if [this](https://forum.doom9.org/showthread.php?p=1910373&highlight=Emulator#post1910373) can help debug this

**Comment by kedaitinh12** [comment] 2021-06-28 04:28
> > @realfinder, @kedaitinh12 can you reproduce the error?
> 
> I can't

me too

**Comment by kedaitinh12** [comment] 2021-06-28 04:35
> The file I downloaded from the link you passed is for compiling, I thought it was another version of Smoothuv2.
> 
> The script you posted doesn't work either.
> 
> Sample:
> http://www.filedropper.com/sample2_1
> 
> Here the script:
> 
> LWLibavVideoSource("Sample2.mp4")
> AssumeFPS("ntsc_film")
> sshiq2(rY=5,rC=5,tY=5,tC=5,str=5,HQC=false,HQY=true)
> 
> Remember that my CPU is e5800 dual core.

are you update vcredist last ver?? @GMJCZP  https://github.com/abbodi1406/vcredist/releases/tag/v0.50.0

**Comment by Asd-g** [comment] 2021-06-28 06:36
Thanks for the feed back.

> 
> 
> don't know if [this](https://forum.doom9.org/showthread.php?p=1910373&highlight=Emulator#post1910373) can help debug this

If I cannot reproduce the error I have nothing to debug.
[There is this](http://avisynth.nl/index.php/FAQ_common_errors#When_frameserving_I_got_the_following_message:_.22CAVIStreamSynth:_System_exception_-_Access_Violation_at_0x0.2C_reading_from_0x0.22.3F).
[Also this](https://forum.doom9.org/showthread.php?p=1350284#post1350284) and [this: fix: memory leak in CAVIStreamSynth (e.g. feeding vdub)](https://forum.doom9.org/showthread.php?p=1808200&highlight=CAVIStreamSynth#post1808200).
I'm just blindly shooting now and the issue could be something completely different.

Edit: @GMJCZP, what happens if use smoothuv2 instead sshiq2?

**Comment by GMJCZP** [comment] 2021-06-28 11:16
Thanks, the last version you uploaded in gofile has finally worked.

But I am noticing that its performance is different from the old version, in fact I try more extreme values and it does practically nothing.

**Comment by Asd-g** [comment] 2021-06-29 02:40
Does this version work again - https://gofile.io/d/8bSmTH ?
> 
> 
> But I am noticing that its performance is different from the old version, in fact I try more extreme values and it does practically nothing.

Can you show what you tried and what's different?

**Comment by GMJCZP** [comment] 2021-06-29 14:26
> Does this version work again - https://gofile.io/d/8bSmTH ?
> 
> > But I am noticing that its performance is different from the old version, in fact I try more extreme values and it does practically nothing.
> 
> Can you show what you tried and what's different?

Sample SSHiq:
http://www.filedropper.com/samplesshiq

Sample sshiq2:
http://www.filedropper.com/samplesshiq2

In the two samples, observe for example in frame 110 the red pants and you will notice that with the extreme values of

(rY = 7, rC = 7, tY = 7, tC = 7, str = 50, HQC = false, HQY = true)

sshiq does its job but with sshiq2 it does almost nothing, this is what I mean they do not have the same performance.

**Comment by kedaitinh12** [comment] 2021-06-29 16:30
You can use https://postimages.org/ for upload samples

**Comment by Asd-g** [comment] 2021-06-29 19:12
I used the compiled plugin included in "smoothuv_dll_20030902.zip" from [here](http://avisynth.nl/index.php/SmoothUV) to make the comparisons.
Check the results - https://imgbox.com/g/K5ja45BMEB
Note how the output for sshiq(..str=50) and sshiq(...str=250) is almost identical.

Btw the plugin included in "smoothuv_dll_20030902.zip" is compiled from other source not the one included in "smoothuv_dll_20030902.zip".

**Comment by realfinder** [comment] 2021-06-29 21:52
yes it seems smoothuv src is for v1.3.1 or even 1.3

**Comment by Asd-g** [comment] 2021-06-29 22:30
It's even for earlier version than 1.3 because radius > 5 is not allowed.

**Comment by kedaitinh12** [comment] 2021-06-30 02:32
Don't forget download new ver @GMJCZP
https://github.com/Asd-g/AviSynth-SmoothUV2/releases

**Comment by GMJCZP** [comment] 2021-06-30 11:18
Thanks for your efforts, I downloaded version 4.2.1 and I keep noticing the same problem, I am using the old version 1.4.0 from 09/02/2003.

**Comment by Asd-g** [comment] 2021-06-30 11:33
Do you mean the different behavior of sshiq(str=x) and sshiq2(str=x) by writing "the same problem"?

**Comment by kedaitinh12** [comment] 2021-06-30 12:11
> Thanks for your efforts, I keep noticing the same problem

I don't think it's problem. Cause SSHiQ(str=50) don't identical str=250 while SSHiQ2(str=50) different str=250. I think it's a updated and easy to use than old ver for different cases

**Comment by GMJCZP** [comment] 2021-06-30 18:13
For this values of sshiq(rY = 7, rC = 7, tY = 7, tC = 7, str = 50, HQC = false, HQY = true) and sshiq2(rY = 7, rC = 7, tY = 7, tC = 7, str = 50, HQC = false, HQY = true)  the behavior is different. See the samples at this same values.

**Comment by Asd-g** [comment] 2021-06-30 18:39
@GMJCZP , did you read [this](https://github.com/Asd-g/AviSynth-SmoothUV2/issues/2#issuecomment-870847391):

> 
> 
> I used the compiled plugin included in "smoothuv_dll_20030902.zip" from [here](http://avisynth.nl/index.php/SmoothUV) to make the comparisons.
> Check the results - https://imgbox.com/g/K5ja45BMEB
> Note how the output for sshiq(..str=50) and sshiq(...str=250) is almost identical.
> 
> Btw the plugin included in "smoothuv_dll_20030902.zip" is compiled from other source not the one included in "smoothuv_dll_20030902.zip".

sshiq with strength 50 and strength 250 has almost identical output: strength from 0 to 255 doesn't smooth evenly - from 0-50 it smooth very aggressively and from 50-255 it smooth almost nothing.

sshiq2 with strength 50 lightly smooth and with strength 250 behaves very aggressively (even more aggressive than sshiq with strength 250): strength from 0 to 255 smooth evenly.

**Comment by GMJCZP** [comment] 2021-07-01 04:19
No one is understanding me, the idea is that with the arguments that I have previously published several times, the same result is produced, which is not the case, as I have already said several times. Let's change the word "behavior" to "result", to see if you understand me now. Wasn't the whole point of having a version of sshiq for HBD called sshiq2? So why isn't getting the same result given certain arguments? I don't know what else to do to make them understand me, I have asked them several times to observe the samples, in them it can be clearly seen that they are different because sshiq2 does not produce the same results as SSHiq given the same arguments. You can take the original sample that I have also uploaded and do the test yourself and then you will understand better what I have been saying over and over again,...

**Comment by GMJCZP** [comment] 2021-07-01 04:30
...Unless you have to do an interpolation of values, as you say Asd-g, like this, for example: min-max strength SSHiq = 0-50, for sshiq2 min-max strength = 0-255, I think I understand now what what are you trying to tell me. If this is true, how could you make the equivalence of values? And if this is not either then I would no longer know what to do.

**Comment by kedaitinh12** [comment] 2021-07-01 04:40
> If this is true, how could you make the equivalence of values?

Asd-g use some test in here:
https://imgbox.com/g/K5ja45BMEB

And i will uploade result in here if you don't view images of result
![kzCilaA1_o](https://user-images.githubusercontent.com/66716952/124065390-ee05b880-da60-11eb-8fc1-2bebc66306c4.png)
![4KyoHs6U_o](https://user-images.githubusercontent.com/66716952/124065435-083f9680-da61-11eb-93ad-42b0083aa9ab.png)
![dlF1Dplj_o](https://user-images.githubusercontent.com/66716952/124065443-0c6bb400-da61-11eb-8b9d-cb4f2bd49dd6.png)
![UgqJQfrU_o](https://user-images.githubusercontent.com/66716952/124065455-12fa2b80-da61-11eb-9373-4ce59d7f80d4.png)
![fayvDSKY_o](https://user-images.githubusercontent.com/66716952/124065461-15f51c00-da61-11eb-8f35-69ddc613ed02.png)

**Comment by GMJCZP** [comment] 2021-07-01 04:55
My original belief was to just get a version of SSHiq for HBD. Once this was achieved after manifesting the two bugs that I discovered but Asd-g apparently already discovered one: the behavior of the "str" argument, although its original manual says that its values are 0-255, it really seems that it was 0 to about 50. The other bug is with HQC, I put it in "false" because otherwise some colors appear changed, this I could never channel until Asd-g has taken the trouble to revive this filter, which I appreciate.

I have had to live with these two bugs until now but it seems that Asd-g has already corrected the one with "str".

**Comment by kedaitinh12** [comment] 2021-07-01 05:09
> The other bug is with HQC, I put it in "false" because otherwise some colors appear changed, this I could never channel until Asd-g has taken the trouble to revive this filter, which I appreciate.

Lol, i think you need say clearly and provide sample results before. I think Asd-g busy and he release many filters. He don't take care about only one fileter like SmoothUV2. You should be more sympathetic towards him. He just add this and don't knowledge about this filter like you cause you use SSHiQ many time than him. So you need say clearly your problems and don't to give an equivocal answer like "the same problem??"

**Comment by Asd-g** [comment] 2021-07-01 05:41
>The other bug is with HQC, I put it in "false" because otherwise some colors appear changed...

@GMJCZP, try sshiq2(rY = 7, rC = 7, tY = 7, tC = 7, str = 250, HQC = true, HQY = true): there are other changes than "str" under the hood that make chroma looks differently in sshiq and sshiq2.

![New File (4)000110](https://user-images.githubusercontent.com/65298684/124071226-b6d6dd80-da47-11eb-9073-aac5f0b3121a.png)
![New File (2)000110](https://user-images.githubusercontent.com/65298684/124071256-be968200-da47-11eb-8932-7ef0c1248d9a.png)
![New File (3)000110](https://user-images.githubusercontent.com/65298684/124071268-c0604580-da47-11eb-8a5a-9bd41688b165.png)

Actually it would be better if I separate "str" to "strY" and "strC".

**Comment by GMJCZP** [comment] 2021-07-01 05:52
Thanks Asd-g. Now I must do this and other tests, I do not know if you understood the interpolation or equivalence of values for "str", I think that as long as it is linear its behavior should not be a problem of adaptation from sshiq to sshiq2, I hope so.

**Comment by GMJCZP** [comment] 2021-07-01 11:07
He was able to confirm that with HQC = true fortunately the colors are kept.

What worries me now is the encoding speed, I have noticed that sshiq2 is slower than sshiq, as can be seen in this report made with Avsmeter:

For SShiq:

[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          10.72 | 18.68 | 18.27
Process memory usage (max):         32 MiB
Thread count:                       6
CPU usage (average):                59.4%

Time (elapsed):                     00:00:08.867

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq(rY=7,rC=7,tY=7,tC=7,str=50,HQC=false,HQY=true)


For SShiq2:

[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          4.592 | 5.679 | 5.620
Process memory usage (max):         32 MiB
Thread count:                       6
CPU usage (average):                53.1%

Time (elapsed):                     00:00:28.826

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,str=250,HQC=false,HQY=true)

**Comment by Asd-g** [comment] 2021-07-01 12:10
> 
> He was able to confirm that with HQC = true fortunately the colors are kept.

Good to hear it's ok.

> 
> What worries me now is the encoding speed, I have noticed that sshiq2 is slower than sshiq...

This is expected mainly because plain C++ code is used (for CPUs without SSE4.1) and it seems the compiler cannot optimize the code enough to get performance closer to the one with MMX (sshiq).
Sorry, but I'll not do any MMX optimizations.

**Comment by kedaitinh12** [comment] 2021-07-01 13:24
True, in present many new plugins don't support MMX anymore

**Comment by GMJCZP** [comment] 2021-07-01 20:53
> > What worries me now is the encoding speed, I have noticed that sshiq2 is slower than sshiq...
> 
> This is expected mainly because plain C++ code is used (for CPUs without SSE4.1) and it seems the compiler cannot optimize the code enough to get performance closer to the one with MMX (sshiq).
> Sorry, but I'll not do any MMX optimizations.

I appreciate the effort but nothing can be done? It is more than three times as slow.

**Comment by GMJCZP** [comment] 2021-07-01 21:14
I took the liberty of comparing the performance of Cnr2 2016 with vsCnr2 and these are the results:

For cnr2:

[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          64.28 | 142.3 | 110.9
Process memory usage (max):         34 MiB
Thread count:                       6
CPU usage (average):                68.3%

Time (elapsed):                     00:00:01.461

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
cnr2()


For vscnr2:

[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          54.61 | 134.1 | 104.2
Process memory usage (max):         34 MiB
Thread count:                       6
CPU usage (average):                70.3%

Time (elapsed):                     00:00:01.555

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
vscnr2()

Although I admit that the time is short for a reliable comparison it can be seen that the times are very similar, could not a similar adaptation be made for SSHiq?

**Comment by Asd-g** [comment] 2021-07-01 21:51
With plain C++ code the filtering is done by processing pixel by pixel.
With MMX/SSE/AVX the filtering could be done by processing few pixels (2/4/8/16..) simultaneously.

Cnr2 is plain C++ code. vsCnr2 is also plain C++ code.

SSHIQ is not plain C++ code. It has MMX optimization. SSHIQ2(opt=0) is plain C++ code. SSHIQ process 4 pixels simultaneously and SSHIQ2(opt=0) process pixel by pixel.
An eventual MMX optimization will process 2 pixels simultaneously with the changes of how internally work SSHIQ2. It would be ~2x faster than SSHIQ2(opt=0) and still ~50% slower than SSHIQ.
If I would spend time to add different optimization I prefer to add not already obsolete one (MMX) but AVX2/AVX512.

**Comment by realfinder** [comment] 2021-07-02 02:08
MMX is so old yes, but for GMJCZP there can be sse and sse2, in x64 it's sse2 at least

**Comment by kedaitinh12** [comment] 2021-07-02 02:12
Me too, i think you can add sse2 for old cpu same almost plugins in present like pinterf plugins

**Comment by kedaitinh12** [comment] 2021-07-02 02:43
His CPU support sse -> ssse3
![Screenshot_20210702_094231](https://user-images.githubusercontent.com/66716952/124212918-f79f2700-db19-11eb-9c02-712c9b1af93a.jpg)

**Comment by Asd-g** [comment] 2021-07-03 22:21
@GMJCZP, you can try the latest version.

**Comment by GMJCZP** [comment] 2021-07-04 12:53
Thanks for the new version. I did a test with AvsMeter for a comparison and here are the results:

[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          9.098 | 13.67 | 13.39
Process memory usage (max):         32 MiB
Thread count:                       6
CPU usage (average):                56.7%

Time (elapsed):                     00:00:12.098

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,stry=250,strc=250,HQC=true,HQY=true)

As you can see the speed now is more than doubled (28s versus 12s), but it is still slower than SSHiq (12s versus 8s).
Seeing these results, wouldn't it be possible to add the other SSE3 and SSSE3 instructions, as the Kassandro filters have for example?

**Comment by kedaitinh12** [comment] 2021-07-05 11:51
Strange, why sse2 code slower than mmx code???

**Comment by Asd-g** [comment] 2021-07-05 12:45
> Seeing these results, wouldn't it be possible to add the other SSE3 and SSSE3 instructions, as the Kassandro filters have for example?

Added in the latest version.

> Strange, why sse2 code slower than mmx code???

Is it?

It seems you're assuming that everything is same when comparing mmx and sse2. It's not. SmoothUV2/SSHIQ2 and SmoothUV/SSHIQ have differences how they work internally (the main difference is the former works in 16-bit depth internally).

However I don't get the same results like @GMJCZP.

SSHIQ
```
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq(rY=7,rC=7,tY=7,tC=7,str=50,HQC=true,HQY=true)
```
The result:
```
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          9.822 | 31.70 | 28.61
Process memory usage (max):         113 MiB
Thread count:                       42
CPU usage (average):                6.6%

Time (elapsed):                     00:00:05.663
```

SSHIQ2(opt=1)
```
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,stry=250,HQC=true,HQY=true, opt=1)
```
The result:
```
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          9.065 | 36.51 | 33.24
Process memory usage (max):         114 MiB
Thread count:                       42
CPU usage (average):                7.5%

Time (elapsed):                     00:00:04.874
```

**Comment by GMJCZP** [comment] 2021-07-05 20:27
Thanks, in this version is both SSE3 and SSSE3 present? Well I see you only mention SSSE3.

**Comment by kedaitinh12** [comment] 2021-07-05 23:48
Only SSSE3

**Comment by Asd-g** [comment] 2021-07-06 05:43
> 
> 
> Thanks, in this version is both SSE3 and SSSE3 present? Well I see you only mention SSSE3.

There are no SSE3 intrinsics that can be used here.

**Comment by GMJCZP** [comment] 2021-07-06 11:07
> > Thanks, in this version is both SSE3 and SSSE3 present? Well I see you only mention SSSE3.
> 
> There are no SSE3 intrinsics that can be used here.

Ok, I did another tests and now the time is 9,8s- 10s, almost 20% of increment of speed. 
In short, SSHiq: 8s, sshiq2: 10s.

Thank you again.

**Comment by GMJCZP** [comment] 2021-07-06 11:13
Out of curiosity Asd-g, I was looking at the results of your tests and I noticed that you have a very high Thread Count (42). Did you use Prefetch in your tests? I don't use it because I have problems with it.

**Comment by Asd-g** [comment] 2021-07-06 15:00
I too didn't use prefetch (see the low CPU usage). The scripts I posted are the exactly one I used for the tests.

**Comment by GMJCZP** [comment] 2021-07-06 17:54
> I too didn't use prefetch (see the low CPU usage). The scripts I posted are the exactly one I used for the tests.

Wow! How many cores/threads does your cpu have?

**Comment by kedaitinh12** [comment] 2021-07-07 03:42
If don't have any problem more, time to close issue

**Comment by GMJCZP** [comment] 2021-07-07 10:56
> > I too didn't use prefetch (see the low CPU usage). The scripts I posted are the exactly one I used for the tests.
> 
> Wow! How many cores/threads does your cpu have?

I ask this because if it would be feasible to add to SmoothUV the option that it be internally Multithreaded in order to increase the speed, such as Dfttest.

**Comment by Asd-g** [comment] 2021-07-10 17:12
> I ask this because if it would be feasible to add to SmoothUV the option that it be internally Multithreaded in order to increase the speed, such as Dfttest.
Dfttest is using fftw lib that has option for multithreading. Dfttest is itself is not multithreaded but fftw.

Generally openmp could be used for some internal multithreading like jincresize but using prefetch is more efficient.

I don't know what problems you have with prefetch but I'm sharing result without prefetch and with prefetch():

Without prefetch (SSE4.1):
```
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,stry=250,HQC=true,HQY=true)
# prefetch()
```
The result:
```
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          18.03 | 49.95 | 46.84
Process memory usage (max):         121 MiB
Thread count:                       42
CPU usage (average):                6.9%

Time (elapsed):                     00:00:03.459
```
With prefetch() (SSE4.1)
```
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,stry=250,HQC=true,HQY=true)
prefetch()
```
The result:
```
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          34.31 | 178571 | 228.3
Process memory usage (max):         152 MiB
Thread count:                       53
CPU usage (average):                22.8%

Time (elapsed):                     00:00:00.709
```

**Comment by GMJCZP** [comment] 2021-07-10 21:53
Thanks for sharing your tests, by the way the time does not appear with Prefetch, but you can see that it is faster using it than not.

The problem I have (and so does pinterf with your i7 7700) is that with Prefetch (2) it is worse than not using it, it seems like a bottleneck problem:

https://forum.doom9.org/showthread.php?p=1943778#post1943778

This problem is so serious that Doom9 user Boulder told me that Avs + is not applicable for multithreading. That is why I have raised the issue of an internally multithreading version of SmoothUv2.

**Comment by Asd-g** [comment] 2021-07-11 08:44
> Thanks for sharing your tests, by the way the time does not appear with Prefetch, but you can see that it is faster using it than not.

I forgot to include the time. I did the test again with prefetch() and added the time in the previous comment.

> 
> The problem I have (and so does pinterf with your i7 7700) is that with Prefetch (2) it is worse than not using it, it seems like a bottleneck problem:
> 
> https://forum.doom9.org/showthread.php?p=1943778#post1943778
> 
> This problem is so serious that Doom9 user Boulder told me that Avs + is not applicable for multithreading. That is why I have raised the issue of an internally multithreading version of SmoothUv2.

Test the following script with and without prefetch:
```
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,stry=250,HQC=true,HQY=true)
prefetch() # and without prefetch
```

**Comment by GMJCZP** [comment] 2021-07-11 13:19
With Prefetch():


[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          2.819 | 389654 | 26.10
Process memory usage (max):         41 MiB
Thread count:                       9
CPU usage (average):                93.2%

Time (elapsed):                     00:00:06.208

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,stry=250,strc=250,HQC=true,HQY=true)
Prefetch()


Without Prefetch():

[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          10.45 | 16.50 | 16.14
Process memory usage (max):         32 MiB
Thread count:                       6
CPU usage (average):                57.5%

Time (elapsed):                     00:00:10.035

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
sshiq2(rY=7,rC=7,tY=7,tC=7,stry=250,strc=250,HQC=true,HQY=true)

**EDIT**: tests without sshiq2:

With Prefetch():


[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          0.328 | 283385 | 5.220
Process memory usage (max):         39 MiB
Thread count:                       9
CPU usage (average):                80.7%

**Time (elapsed):                     00:00:31.035**

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
Prefetch()


Without Prefetch():

[Runtime info]
Frames processed:                   162 (0 - 161)
FPS (min | max | average):          93.83 | 151.0 | 123.4
Process memory usage (max):         31 MiB
Thread count:                       6
CPU usage (average):                66.3%

Time (elapsed):                     00:00:01.312

[Script]
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)

It's unheard of, why is it better for Prefetch to have a plugin like sshiq2 in the filter chain? Does it have to do with the instructions? It is something surreal. Then would have to create a plugin called "Dummy" to help Prefetch, like sshiq2 circumstantially does. Something like that:

SourceFilter()
AssumeFps()
Dummy()
Prefetch()

Dummy should be something like NOP () but with the circumstantial advantages of Sshiq2.

**Comment by Asd-g** [comment] 2021-07-11 15:47
```
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
convertbits(8)
```

Why would you use prefetch for the above script? Is it the bottleneck in your encoding chain?

Something to take in mind: convertbits is fast filter. fps after convertbits are very high meaning fps in the input of convertbits should be at least 2x/4x (depends on prefetch(x)) higher than those after the filter otherwise using prefetch will lead to speed penalty.
On the other hand sshiq2 is relatively slow filter: fps in the input of sshiq2 can be lower compared to the fps in the input of convertbits.
In nutshell fps from the source filter are enough to take advantage of prefetch for sshiq2 and not enough for convertbits.

One tip: use prefetch only when it's really needed. I doubt the above script will be the bottleneck of the entire encoding chain in 99.99% of the cases.

**Comment by GMJCZP** [comment] 2021-07-11 20:49
I just did some tests with the same script in my previous post but this time without convertbits (8):

Without Prefetch (): 10s
With Prefetch (): 15s (more slow).

What I notice is that while the script is made simpler Prefetch it slows down everything, how is it explained, as you can see in my previous post, from 1s to 31s? it is astonishing and regrettable at the same time.
The only time Prefetch does its job is in the presence of the sshiq2 script (from 10s Prefetch took things to 6s).

I remember when I was using the old avisynth and SEt's SetMTMode, something like this never happened to me.

**Comment by realfinder** [comment] 2021-07-11 23:14
as said before, it's not Prefetch problem, https://forum.doom9.org/showthread.php?p=1944911#post1944911 and I got temporary solution for it https://forum.doom9.org/showthread.php?p=1944654#post1944654 until the problem is resolved in avs+ side by adding new MT_LINEARIZED for Source Filters or whatever solution

**Comment by Asd-g** [comment] 2021-07-12 09:49
```
LWLibavVideoSource("Sample2.mp4")
AssumeFPS("ntsc_film")
```

As already said by @realfinder and in doom9 using prefetch in the above script means that you're practically trying to use prefetch on source filter (AssumeFPS doesn't get frames). That (using prefetch) will not work (with the current implementations), period. Source filters are already multithreaded and they are not bottleneck.

> What I notice is that while the script is made simpler Prefetch it slows down everything, how is it explained, as you can see in my previous post, from 1s to 31s?

Already answered in my previous comment.

I'm closing this because the latest comments are off and do not have anything related to sshiq(2).

**Closed as completed by Asd-g** 2021-07-12 09:49 UTC
